sudo: required

service: docker

before_install:
  - docker login -u awkward37 -p dckr_pat_G9AMGb1a2oBKfP9LdsJATDREOEE
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test